BUG: Fixed circular import error caught at deploy
Heroku throws an error 'ImportError: cannot import name 'app' from
partially initialized module 'budgify' (most likely due to a circular
import) (/app/budgify/__init__.py).' Likely caused by importing
routes.py into top of __init__.py file instead of the bottom.